/*
###############################################################
#  Generated by:      Cadence Innovus 20.14-s095_1
#  OS:                Linux x86_64(Host ID cad28)
#  Generated on:      Fri Oct 31 15:56:34 2025
#  Design:            pe64_lookahead
#  Command:           saveNetlist pe64_lookahead.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Oct 31 2025 14:50:52 IST (Oct 31 2025 09:20:52 UTC)
// Verification Directory fv/pe64_lookahead 
module pe64_lookahead (
	d, 
	q, 
	v);
   input [63:0] d;
   output [5:0] q;
   output v;

   // Internal wires
   wire FE_RN_2;
   wire FE_RN_15_0;
   wire FE_OCPN16_n_97;
   wire FE_OCPN15_n_55;
   wire FE_OCPN14_n_57;
   wire FE_OCPN13_n_51;
   wire FE_OCPN12_FE_OFN0_n_89;
   wire FE_RN_14_0;
   wire FE_OCPN11_FE_DBTN0_n_162;
   wire FE_OCPN9_FE_DBTN0_n_162;
   wire FE_RN_13_0;
   wire FE_RN_12_0;
   wire FE_RN_11_0;
   wire FE_RN_10_0;
   wire FE_RN_9_0;
   wire FE_RN_8_0;
   wire FE_RN_7_0;
   wire FE_RN_6_0;
   wire FE_OCPN8_n_89;
   wire FE_OCPN7_n_63;
   wire FE_RN_1;
   wire FE_RN_5_0;
   wire FE_RN_4_0;
   wire FE_OCPN5_n_162;
   wire FE_OCPN4_n_84;
   wire FE_RN_3_0;
   wire FE_RN_2_0;
   wire FE_RN_1_0;
   wire FE_OCPN3_n_87;
   wire FE_OCPN1_n_97;
   wire FE_RN_0_0;
   wire FE_OCPN2_n_162;
   wire FE_OFN0_n_89;
   wire FE_DBTN1_q_3;
   wire FE_DBTN0_n_162;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_49;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_77;
   wire n_78;
   wire n_80;
   wire n_84;
   wire n_86;
   wire n_87;
   wire n_89;
   wire n_92;
   wire n_97;
   wire n_98;
   wire n_99;
   wire n_100;
   wire n_104;
   wire n_108;
   wire n_109;
   wire n_110;
   wire n_115;
   wire n_117;
   wire n_118;
   wire n_120;
   wire n_121;
   wire n_122;
   wire n_123;
   wire n_124;
   wire n_127;
   wire n_129;
   wire n_130;
   wire n_132;
   wire n_133;
   wire n_134;
   wire n_135;
   wire n_137;
   wire n_138;
   wire n_139;
   wire n_140;
   wire n_141;
   wire n_142;
   wire n_143;
   wire n_144;
   wire n_145;
   wire n_146;
   wire n_147;
   wire n_148;
   wire n_149;
   wire n_150;
   wire n_151;
   wire n_152;
   wire n_153;
   wire n_154;
   wire n_156;
   wire n_158;
   wire n_159;
   wire n_160;
   wire n_161;
   wire n_162;
   wire n_163;
   wire n_164;
   wire n_165;
   wire n_166;
   wire n_167;
   wire n_168;
   wire n_169;
   wire n_170;
   wire n_171;
   wire n_172;
   wire n_173;
   wire n_174;
   wire n_175;
   wire n_176;
   wire n_178;
   wire n_179;
   wire n_180;
   wire n_181;
   wire n_182;
   wire n_183;
   wire n_184;
   wire n_185;
   wire n_186;
   wire n_187;
   wire n_188;
   wire n_189;
   wire n_274;
   wire n_278;
   wire n_280;
   wire n_282;
   wire n_283;
   wire n_288;
   wire n_290;

   NAND3X2 FE_RC_43_0 (.A(FE_OCPN9_FE_DBTN0_n_162),
	.B(FE_RN_2),
	.C(d[3]),
	.Y(n_159));
   INVX2 g3941_dup (.A(n_130),
	.Y(FE_RN_2));
   NAND4X2 FE_RC_42_0 (.A(n_167),
	.B(n_168),
	.C(n_170),
	.D(n_143),
	.Y(FE_RN_3_0));
   INVX4 FE_RC_40_0 (.A(FE_RN_14_0),
	.Y(FE_RN_15_0));
   NOR2X4 FE_RC_39_0 (.A(FE_RN_15_0),
	.B(n_32),
	.Y(FE_RN_13_0));
   CLKBUFX3 FE_OCPC16_n_97 (.A(FE_OCPN1_n_97),
	.Y(FE_OCPN16_n_97));
   BUFX1 FE_OCPC15_n_55 (.A(n_55),
	.Y(FE_OCPN15_n_55));
   BUFX1 FE_OCPC14_n_57 (.A(n_57),
	.Y(FE_OCPN14_n_57));
   CLKBUFX3 FE_OCPC13_n_51 (.A(n_51),
	.Y(FE_OCPN13_n_51));
   CLKBUFX3 FE_OCPC12_FE_OFN0_n_89 (.A(FE_OFN0_n_89),
	.Y(FE_OCPN12_FE_OFN0_n_89));
   AOI22X2 FE_RC_38_0 (.A0(n_144),
	.A1(d[42]),
	.B0(n_145),
	.B1(d[10]),
	.Y(n_143));
   NOR2X4 FE_RC_37_0 (.A(d[17]),
	.B(d[18]),
	.Y(FE_RN_14_0));
   CLKBUFX3 FE_OCPC11_FE_DBTN0_n_162 (.A(FE_DBTN0_n_162),
	.Y(FE_OCPN11_FE_DBTN0_n_162));
   BUFX2 FE_OCPC9_FE_DBTN0_n_162 (.A(FE_DBTN0_n_162),
	.Y(FE_OCPN9_FE_DBTN0_n_162));
   NAND2X4 FE_RC_34_0 (.A(FE_RN_13_0),
	.B(n_51),
	.Y(n_65));
   INVX1 FE_RC_33_0 (.A(d[49]),
	.Y(FE_RN_11_0));
   NAND2BX1 FE_RC_32_0 (.AN(FE_RN_11_0),
	.B(n_139),
	.Y(FE_RN_12_0));
   NAND3X2 FE_RC_31_0 (.A(FE_RN_12_0),
	.B(n_152),
	.C(n_135),
	.Y(n_176));
   NOR2X4 FE_RC_30_0 (.A(d[61]),
	.B(d[62]),
	.Y(FE_RN_10_0));
   NAND2X4 FE_RC_29_0 (.A(FE_RN_10_0),
	.B(FE_RN_4_0),
	.Y(n_45));
   AND2X4 FE_RC_28_0 (.A(n_164),
	.B(d[1]),
	.Y(FE_RN_9_0));
   NOR2X2 FE_RC_27_0 (.A(n_176),
	.B(FE_RN_9_0),
	.Y(n_180));
   AOI22X2 FE_RC_26_0 (.A0(FE_OFN0_n_89),
	.A1(d[45]),
	.B0(FE_OCPN1_n_97),
	.B1(d[13]),
	.Y(n_115));
   CLKINVX3 FE_RC_25_0 (.A(FE_RN_6_0),
	.Y(FE_RN_8_0));
   NAND3X2 FE_RC_24_0 (.A(FE_RN_8_0),
	.B(n_127),
	.C(n_122),
	.Y(n_163));
   OAI2BB1X2 FE_RC_23_0 (.A0N(d[59]),
	.A1N(FE_DBTN0_n_162),
	.B0(n_134),
	.Y(n_166));
   AOI21XL FE_RC_22_0 (.A0(n_52),
	.A1(n_87),
	.B0(n_80),
	.Y(FE_RN_7_0));
   NAND2X1 FE_RC_21_0 (.A(FE_RN_7_0),
	.B(n_99),
	.Y(n_110));
   NAND3BX4 FE_RC_20_0 (.AN(n_283),
	.B(n_73),
	.C(n_71),
	.Y(n_84));
   NOR2X2 FE_RC_19_0 (.A(n_162),
	.B(n_1),
	.Y(FE_RN_6_0));
   BUFX1 FE_OCPC8_n_89 (.A(n_89),
	.Y(FE_OCPN8_n_89));
   BUFX2 FE_OCPC7_n_63 (.A(n_63),
	.Y(FE_OCPN7_n_63));
   AND2X4 g3946__9315_dup (.A(FE_DBTN1_q_3),
	.B(FE_OCPN12_FE_OFN0_n_89),
	.Y(FE_RN_1));
   AOI21X4 FE_RC_16_0 (.A0(d[7]),
	.A1(FE_RN_2),
	.B0(n_166),
	.Y(FE_RN_5_0));
   NAND3X2 FE_RC_15_0 (.A(FE_RN_5_0),
	.B(FE_RN_0_0),
	.C(n_159),
	.Y(n_183));
   NOR2X4 FE_RC_14_0 (.A(d[60]),
	.B(d[63]),
	.Y(FE_RN_4_0));
   BUFX2 FE_OCPC5_n_162 (.A(n_162),
	.Y(FE_OCPN5_n_162));
   CLKBUFX3 FE_OCPC4_n_84 (.A(n_84),
	.Y(FE_OCPN4_n_84));
   CLKINVX3 FE_RC_11_0 (.A(FE_RN_3_0),
	.Y(n_188));
   INVXL FE_RC_7_0 (.A(d[41]),
	.Y(FE_RN_1_0));
   NAND2BX2 FE_RC_6_0 (.AN(FE_RN_1_0),
	.B(n_144),
	.Y(FE_RN_2_0));
   OAI2BB1X2 FE_RC_5_0 (.A0N(n_145),
	.A1N(d[9]),
	.B0(FE_RN_2_0),
	.Y(n_160));
   CLKBUFX3 FE_OCPC3_n_87 (.A(n_87),
	.Y(FE_OCPN3_n_87));
   BUFX3 FE_OCPC4_n_97 (.A(n_97),
	.Y(FE_OCPN1_n_97));
   AND2X2 FE_RC_4_0 (.A(n_147),
	.B(n_133),
	.Y(FE_RN_0_0));
   BUFX2 FE_OCPC2_n_162 (.A(n_162),
	.Y(FE_OCPN2_n_162));
   NAND3X2 FE_RC_2_0 (.A(n_180),
	.B(n_179),
	.C(n_178),
	.Y(n_185));
   AOI21X2 FE_RC_0_0 (.A0(FE_DBTN0_n_162),
	.A1(d[57]),
	.B0(n_129),
	.Y(n_156));
   BUFX2 FE_OFC3_n_89 (.A(n_89),
	.Y(FE_OFN0_n_89));
   INVXL FE_OFC2_n_89 (.A(FE_OCPN8_n_89),
	.Y(q[4]));
   INVX4 FE_DBTC1_q_3 (.A(q[3]),
	.Y(FE_DBTN1_q_3));
   INVX4 FE_DBTC0_n_162 (.A(n_162),
	.Y(FE_DBTN0_n_162));
   NAND2XL g3890__2398 (.A(n_189),
	.B(n_186),
	.Y(q[0]));
   NAND4XL g3891__5107 (.A(n_182),
	.B(n_184),
	.C(n_187),
	.D(n_188),
	.Y(q[1]));
   NAND3X2 g3892__6260 (.A(n_185),
	.B(n_188),
	.C(n_187),
	.Y(n_189));
   NOR2X1 g3894__4319 (.A(n_183),
	.B(n_181),
	.Y(n_186));
   CLKINVX2 g3895 (.A(n_183),
	.Y(n_184));
   AND3X4 g3899__5526 (.A(n_175),
	.B(n_165),
	.C(n_172),
	.Y(n_187));
   INVX1 g3897 (.A(n_181),
	.Y(n_182));
   NOR2X2 g3902__2802 (.A(n_173),
	.B(n_160),
	.Y(n_179));
   NAND4X2 g3898__1705 (.A(n_171),
	.B(n_146),
	.C(n_140),
	.D(n_142),
	.Y(n_181));
   AOI21X2 g3907__5122 (.A0(n_174),
	.A1(d[33]),
	.B0(n_161),
	.Y(n_178));
   NAND2X2 g3912__6131 (.A(d[34]),
	.B(n_174),
	.Y(n_175));
   NAND3X2 g3903__1881 (.A(n_154),
	.B(n_137),
	.C(n_156),
	.Y(n_173));
   AOI21X1 g3904__5115 (.A0(d[50]),
	.A1(n_139),
	.B0(n_163),
	.Y(n_172));
   AOI21X2 g3920__7482 (.A0(n_169),
	.A1(d[39]),
	.B0(n_153),
	.Y(n_171));
   AOI21X4 g3921__4733 (.A0(n_169),
	.A1(d[38]),
	.B0(n_151),
	.Y(n_170));
   NAND2X2 g3910__6161 (.A(d[18]),
	.B(n_149),
	.Y(n_168));
   AOI21X2 g3919__9315 (.A0(n_141),
	.A1(d[26]),
	.B0(n_138),
	.Y(n_167));
   NAND2X1 g3909__2883 (.A(d[2]),
	.B(n_164),
	.Y(n_165));
   NOR2BX2 g3914__1666 (.AN(d[17]),
	.B(n_148),
	.Y(n_161));
   NOR2X4 g3938__7410 (.A(n_278),
	.B(FE_OCPN2_n_162),
	.Y(n_174));
   NAND2X2 g3925__5107 (.A(n_158),
	.B(d[5]),
	.Y(n_154));
   NOR2BX1 g3927__6260 (.AN(d[23]),
	.B(n_150),
	.Y(n_153));
   NAND2X4 g3930__4319 (.A(n_169),
	.B(d[37]),
	.Y(n_152));
   NOR2BX4 g3931__8428 (.AN(d[22]),
	.B(n_150),
	.Y(n_151));
   CLKINVX3 g3932 (.A(n_148),
	.Y(n_149));
   NAND3X1 g3911__5526 (.A(FE_RN_1),
	.B(FE_DBTN0_n_162),
	.C(d[35]),
	.Y(n_147));
   AOI22X1 g3917__6783 (.A0(n_145),
	.A1(d[11]),
	.B0(n_144),
	.B1(d[43]),
	.Y(n_146));
   NAND2X1 g3929__1617 (.A(d[27]),
	.B(n_141),
	.Y(n_142));
   NAND2XL g3928__2802 (.A(d[51]),
	.B(n_139),
	.Y(n_140));
   NOR2BX1 g3926__1705 (.AN(d[6]),
	.B(n_130),
	.Y(n_138));
   NAND2X2 g3933__5122 (.A(d[25]),
	.B(n_141),
	.Y(n_137));
   NAND2X1 g3935__7098 (.A(d[21]),
	.B(n_132),
	.Y(n_135));
   AOI21X1 g3936__6131 (.A0(FE_DBTN1_q_3),
	.A1(d[55]),
	.B0(n_121),
	.Y(n_134));
   NAND3X1 g3913__1881 (.A(n_132),
	.B(FE_DBTN0_n_162),
	.C(d[19]),
	.Y(n_133));
   NOR2X2 g3940__5115 (.A(FE_OCPN5_n_162),
	.B(n_130),
	.Y(n_164));
   NAND2X2 g3939__7482 (.A(FE_DBTN0_n_162),
	.B(n_132),
	.Y(n_148));
   OAI21X1 g3937__4733 (.A0(n_8),
	.A1(q[3]),
	.B0(n_120),
	.Y(n_129));
   INVX2 g3941 (.A(n_130),
	.Y(n_158));
   NAND2X2 g3943__6161 (.A(FE_DBTN1_q_3),
	.B(d[54]),
	.Y(n_127));
   INVX4 g3947 (.A(n_132),
	.Y(n_150));
   AND2X4 g3946__9315 (.A(FE_DBTN1_q_3),
	.B(FE_OCPN12_FE_OFN0_n_89),
	.Y(n_169));
   NOR2X1 g3944__9945 (.A(n_162),
	.B(q[3]),
	.Y(n_139));
   NAND2BX4 g3945__2883 (.AN(q[3]),
	.B(FE_OCPN16_n_97),
	.Y(n_130));
   NOR2X2 g3948__2346 (.A(n_162),
	.B(FE_OCPN4_n_84),
	.Y(n_145));
   NOR2X2 g3949__1666 (.A(n_162),
	.B(q[4]),
	.Y(n_144));
   NOR2X2 g3950__7410 (.A(n_162),
	.B(q[5]),
	.Y(n_141));
   NOR2X4 g3951__6417 (.A(q[3]),
	.B(q[5]),
	.Y(n_132));
   NAND2X4 g3953__5477 (.A(n_123),
	.B(n_124),
	.Y(q[3]));
   OAI2BB1X4 g3955__2398 (.A0N(n_110),
	.A1N(n_124),
	.B0(n_123),
	.Y(n_162));
   AND2X4 g3956__5107 (.A(n_118),
	.B(n_108),
	.Y(n_122));
   NAND2X1 g3957__6260 (.A(n_117),
	.B(n_104),
	.Y(n_121));
   AND2X4 g3958__4319 (.A(n_115),
	.B(n_100),
	.Y(n_120));
   NOR2X4 g3959__8428 (.A(n_109),
	.B(n_86),
	.Y(n_123));
   NAND3BXL g3980__5526 (.AN(n_62),
	.B(n_87),
	.C(n_78),
	.Y(v));
   AOI22X1 g3961__6783 (.A0(FE_OCPN1_n_97),
	.A1(d[14]),
	.B0(FE_OFN0_n_89),
	.B1(d[46]),
	.Y(n_118));
   AOI22X1 g3963__3680 (.A0(FE_OCPN1_n_97),
	.A1(d[15]),
	.B0(FE_OFN0_n_89),
	.B1(d[47]),
	.Y(n_117));
   OAI2BB1X4 g3965__1705 (.A0N(FE_OCPN14_n_57),
	.A1N(n_89),
	.B0(n_98),
	.Y(n_109));
   AOI21X1 g3966__5122 (.A0(FE_OCPN3_n_87),
	.A1(d[30]),
	.B0(d[62]),
	.Y(n_108));
   AOI21XL g3972__8246 (.A0(FE_OCPN3_n_87),
	.A1(d[31]),
	.B0(d[63]),
	.Y(n_104));
   AOI2BB1X2 g3962__7098 (.A0N(n_84),
	.A1N(n_59),
	.B0(n_92),
	.Y(n_124));
   AOI21X1 g3969__6131 (.A0(FE_OCPN3_n_87),
	.A1(d[29]),
	.B0(d[61]),
	.Y(n_100));
   NAND2X1 g3968__1881 (.A(n_97),
	.B(n_60),
	.Y(n_99));
   NAND2X2 g3967__5115 (.A(n_97),
	.B(n_61),
	.Y(n_98));
   OAI2BB1X4 g3973__7482 (.A0N(n_56),
	.A1N(n_87),
	.B0(n_290),
	.Y(n_92));
   OAI2BB1X2 g3971__6161 (.A0N(n_54),
	.A1N(n_87),
	.B0(n_46),
	.Y(n_86));
   AOI21X2 g3992__9315 (.A0(n_77),
	.A1(n_75),
	.B0(n_282),
	.Y(n_89));
   INVX4 g3979 (.A(n_84),
	.Y(n_97));
   OAI21X1 g3990__2346 (.A0(n_282),
	.A1(n_274),
	.B0(n_280),
	.Y(n_80));
   INVXL g4004 (.A(n_77),
	.Y(n_78));
   INVXL g4000 (.A(n_87),
	.Y(q[5]));
   NOR2X4 g4001__1666 (.A(n_282),
	.B(n_74),
	.Y(n_87));
   NAND2X4 g4007__6417 (.A(n_66),
	.B(n_68),
	.Y(n_77));
   CLKINVX3 g4003 (.A(n_74),
	.Y(n_75));
   NOR2X4 g4005__5477 (.A(n_67),
	.B(n_65),
	.Y(n_73));
   AND2X4 g4009__2398 (.A(n_70),
	.B(n_69),
	.Y(n_71));
   NAND2X2 g4006__5107 (.A(n_69),
	.B(n_70),
	.Y(n_74));
   CLKINVX4 g4012 (.A(n_67),
	.Y(n_68));
   CLKINVX4 g4016 (.A(n_65),
	.Y(n_66));
   NAND2X4 g4015__4319 (.A(n_55),
	.B(n_53),
	.Y(n_67));
   NOR2X4 g4013__5526 (.A(n_63),
	.B(n_41),
	.Y(n_64));
   NAND4BBX1 g4010__6783 (.AN(n_61),
	.BN(n_60),
	.C(n_59),
	.D(n_35),
	.Y(n_62));
   NOR2X4 g4017__3680 (.A(n_49),
	.B(n_45),
	.Y(n_58));
   NOR2X4 g4014__1617 (.A(n_57),
	.B(n_47),
	.Y(n_70));
   INVX1 g4022 (.A(FE_OCPN15_n_55),
	.Y(n_56));
   INVXL g4021 (.A(n_53),
	.Y(n_54));
   INVXL g4033 (.A(FE_OCPN13_n_51),
	.Y(n_52));
   NOR2X4 g4019__2802 (.A(n_43),
	.B(n_40),
	.Y(n_69));
   INVX1 g4020 (.A(n_45),
	.Y(n_46));
   NOR2X4 g4026__1705 (.A(n_33),
	.B(n_34),
	.Y(n_53));
   INVX1 g4034 (.A(n_43),
	.Y(n_44));
   NOR2X4 g4039__8246 (.A(n_36),
	.B(n_39),
	.Y(n_51));
   NOR2X4 g4028__7098 (.A(n_37),
	.B(n_38),
	.Y(n_55));
   NAND2X4 g4030__6131 (.A(n_26),
	.B(n_31),
	.Y(n_63));
   NAND2X4 g4027__1881 (.A(n_30),
	.B(n_18),
	.Y(n_57));
   NAND2X4 g4031__7482 (.A(n_20),
	.B(n_23),
	.Y(n_47));
   NAND2X4 g4036__4733 (.A(n_16),
	.B(n_19),
	.Y(n_41));
   NAND2X4 g4035__6161 (.A(n_29),
	.B(n_21),
	.Y(n_40));
   NAND2X4 g4040__9315 (.A(n_28),
	.B(n_22),
	.Y(n_43));
   NAND2X4 g4032__9945 (.A(n_24),
	.B(n_25),
	.Y(n_49));
   NAND2X4 g4055__2883 (.A(n_15),
	.B(n_14),
	.Y(n_39));
   NAND2X4 g4053__2346 (.A(n_12),
	.B(n_9),
	.Y(n_38));
   NAND2X4 g4050__1666 (.A(n_7),
	.B(n_2),
	.Y(n_37));
   NAND2X4 g4046__7410 (.A(n_10),
	.B(n_13),
	.Y(n_36));
   OR4X2 g4029__6417 (.A(d[7]),
	.B(d[5]),
	.C(d[6]),
	.D(d[4]),
	.Y(n_60));
   NOR4X1 g4038__5477 (.A(d[2]),
	.B(d[1]),
	.C(d[3]),
	.D(d[0]),
	.Y(n_35));
   NAND2X4 g4047__2398 (.A(n_6),
	.B(n_3),
	.Y(n_34));
   NAND2X4 g4045__5107 (.A(n_0),
	.B(n_288),
	.Y(n_33));
   NAND2X4 g4044__6260 (.A(n_11),
	.B(n_4),
	.Y(n_32));
   NOR4X2 g4042__4319 (.A(d[11]),
	.B(d[10]),
	.C(d[9]),
	.D(d[8]),
	.Y(n_59));
   OR4X4 g4041__8428 (.A(d[14]),
	.B(d[13]),
	.C(d[15]),
	.D(d[12]),
	.Y(n_61));
   NOR2X4 g4059__5526 (.A(d[59]),
	.B(d[56]),
	.Y(n_31));
   NOR2X4 g4049__6783 (.A(d[46]),
	.B(d[45]),
	.Y(n_30));
   NOR2X4 g4051__3680 (.A(d[34]),
	.B(d[33]),
	.Y(n_29));
   NOR2X4 g4057__1617 (.A(d[43]),
	.B(d[41]),
	.Y(n_28));
   NOR2X4 g4060__1705 (.A(d[58]),
	.B(d[57]),
	.Y(n_26));
   NOR2X4 g4061__5122 (.A(d[55]),
	.B(d[52]),
	.Y(n_25));
   NOR2X4 g4062__8246 (.A(d[54]),
	.B(d[53]),
	.Y(n_24));
   NOR2X4 g4054__7098 (.A(d[39]),
	.B(d[36]),
	.Y(n_23));
   NOR2X4 g4064__6131 (.A(d[42]),
	.B(d[40]),
	.Y(n_22));
   NOR2X4 g4065__1881 (.A(d[35]),
	.B(d[32]),
	.Y(n_21));
   NOR2X4 g4056__5115 (.A(d[38]),
	.B(d[37]),
	.Y(n_20));
   NOR2X4 g4063__7482 (.A(d[51]),
	.B(d[50]),
	.Y(n_19));
   NOR2X4 g4052__4733 (.A(d[47]),
	.B(d[44]),
	.Y(n_18));
   NOR2X4 g4043__9315 (.A(d[49]),
	.B(d[48]),
	.Y(n_16));
   INVX8 g4073 (.A(d[22]),
	.Y(n_15));
   INVX8 g4068 (.A(d[21]),
	.Y(n_14));
   INVX8 g4067 (.A(d[20]),
	.Y(n_13));
   CLKINVX8 g4079 (.A(d[27]),
	.Y(n_12));
   CLKINVX8 g4077 (.A(d[19]),
	.Y(n_11));
   CLKINVX8 g4076 (.A(d[23]),
	.Y(n_10));
   CLKINVX8 g4074 (.A(d[24]),
	.Y(n_9));
   INVX1 g4078 (.A(d[53]),
	.Y(n_8));
   CLKINVX8 g4080 (.A(d[26]),
	.Y(n_7));
   CLKINVX8 g4071 (.A(d[30]),
	.Y(n_6));
   CLKINVX8 g4066 (.A(d[16]),
	.Y(n_4));
   INVX8 g4075 (.A(d[28]),
	.Y(n_3));
   CLKINVX8 g4070 (.A(d[25]),
	.Y(n_2));
   INVX1 g4072 (.A(d[58]),
	.Y(n_1));
   CLKINVX8 g4069 (.A(d[31]),
	.Y(n_0));
   INVX1 fopt2 (.A(FE_OCPN11_FE_DBTN0_n_162),
	.Y(q[2]));
   INVXL fopt4085 (.A(n_47),
	.Y(n_274));
   CLKINVX4 fopt4088 (.A(FE_RN_1),
	.Y(n_278));
   INVXL fopt4091 (.A(n_49),
	.Y(n_280));
   NAND2X2 g4011__4092 (.A(n_58),
	.B(n_64),
	.Y(n_282));
   NAND2X2 g4011__6260_0 (.A(n_58),
	.B(n_64),
	.Y(n_283));
   CLKINVX8 fopt4105 (.A(d[29]),
	.Y(n_288));
   AOI2BB1X2 g2 (.A0N(n_283),
	.A1N(n_44),
	.B0(FE_OCPN7_n_63),
	.Y(n_290));
endmodule

