/*
###############################################################
#  Generated by:      Cadence Innovus 20.14-s095_1
#  OS:                Linux x86_64(Host ID cad28)
#  Generated on:      Fri Oct 10 16:26:51 2025
#  Design:            pe64_if_else
#  Command:           saveNetlist pe64_if_else_route.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Oct 10 2025 15:42:17 IST (Oct 10 2025 10:12:17 UTC)
// Verification Directory fv/pe64_if_else 
module pe64_if_else (
	d, 
	q, 
	v);
   input [63:0] d;
   output [5:0] q;
   output v;

   // Internal wires
   wire FE_RN_5_0;
   wire FE_RN_4_0;
   wire FE_RN_3_0;
   wire FE_RN_2_0;
   wire FE_RN_1_0;
   wire FE_RN_0_0;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;
   wire n_78;
   wire n_79;
   wire n_80;
   wire n_81;
   wire n_82;
   wire n_83;
   wire n_84;
   wire n_85;
   wire n_86;
   wire n_87;
   wire n_88;
   wire n_89;
   wire n_90;
   wire n_91;
   wire n_92;
   wire n_93;
   wire n_94;
   wire n_95;
   wire n_96;
   wire n_97;
   wire n_98;
   wire n_99;
   wire n_100;
   wire n_101;
   wire n_102;
   wire n_103;
   wire n_104;
   wire n_105;
   wire n_106;
   wire n_107;
   wire n_108;
   wire n_109;
   wire n_110;
   wire n_111;
   wire n_112;
   wire n_113;
   wire n_114;
   wire n_115;
   wire n_116;
   wire n_117;
   wire n_118;
   wire n_119;
   wire n_120;
   wire n_121;
   wire n_122;
   wire n_123;
   wire n_125;
   wire n_126;
   wire n_127;
   wire n_128;
   wire n_129;
   wire n_130;
   wire n_131;
   wire n_132;
   wire n_133;
   wire n_134;
   wire n_135;
   wire n_136;
   wire n_137;
   wire n_138;
   wire n_139;
   wire n_140;
   wire n_141;
   wire n_142;
   wire n_143;
   wire n_145;
   wire n_148;
   wire n_149;
   wire n_150;
   wire n_151;
   wire n_152;
   wire n_153;
   wire n_154;
   wire n_155;
   wire n_157;
   wire n_158;
   wire n_159;
   wire n_160;
   wire n_162;
   wire n_229;

   OR2X2 FE_RC_11_0 (.A(d[54]),
	.B(d[50]),
	.Y(FE_RN_5_0));
   NOR3X2 FE_RC_10_0 (.A(n_107),
	.B(FE_RN_5_0),
	.C(d[52]),
	.Y(n_114));
   AND2X2 FE_RC_9_0 (.A(n_130),
	.B(n_10),
	.Y(FE_RN_4_0));
   NAND3X1 FE_RC_8_0 (.A(n_132),
	.B(n_78),
	.C(FE_RN_4_0),
	.Y(n_152));
   NAND2BX1 FE_RC_7_0 (.AN(d[24]),
	.B(n_33),
	.Y(FE_RN_3_0));
   NOR3X1 FE_RC_6_0 (.A(n_137),
	.B(FE_RN_3_0),
	.C(d[25]),
	.Y(n_141));
   AOI2BB1X1 FE_RC_5_0 (.A0N(n_56),
	.A1N(d[4]),
	.B0(d[5]),
	.Y(n_97));
   NOR4X2 FE_RC_4_0 (.A(d[46]),
	.B(d[44]),
	.C(d[42]),
	.D(d[40]),
	.Y(n_113));
   NOR2X1 FE_RC_3_0 (.A(n_102),
	.B(n_89),
	.Y(FE_RN_0_0));
   INVX1 FE_RC_2_0 (.A(n_139),
	.Y(FE_RN_1_0));
   INVX1 FE_RC_1_0 (.A(n_109),
	.Y(FE_RN_2_0));
   NAND3X1 FE_RC_0_0 (.A(FE_RN_2_0),
	.B(FE_RN_1_0),
	.C(FE_RN_0_0),
	.Y(n_140));
   NAND3X1 g3503__2398 (.A(n_162),
	.B(n_158),
	.C(n_148),
	.Y(q[0]));
   OAI21XL g3504__5107 (.A0(n_159),
	.A1(n_116),
	.B0(n_96),
	.Y(q[2]));
   OAI31X1 g3506__6260 (.A0(n_157),
	.A1(n_119),
	.A2(d[29]),
	.B0(n_136),
	.Y(n_162));
   OAI2BB1XL g3505__4319 (.A0N(n_151),
	.A1N(n_141),
	.B0(n_160),
	.Y(q[1]));
   AOI211XL g3507__8428 (.A0(n_123),
	.A1(n_86),
	.B0(n_138),
	.C0(n_155),
	.Y(n_160));
   AOI31X1 g3509__5526 (.A0(n_154),
	.A1(n_17),
	.A2(n_59),
	.B0(n_67),
	.Y(n_159));
   OAI21XL g3508__6783 (.A0(n_153),
	.A1(d[49]),
	.B0(n_114),
	.Y(n_158));
   AOI31X1 g3510__3680 (.A0(n_152),
	.A1(n_131),
	.A2(n_36),
	.B0(n_35),
	.Y(n_157));
   OAI31X1 g3511__1617 (.A0(n_150),
	.A1(n_115),
	.A2(n_81),
	.B0(n_108),
	.Y(q[3]));
   OAI21XL g3513__2802 (.A0(n_110),
	.A1(n_85),
	.B0(n_149),
	.Y(n_155));
   OAI211X1 g3515__1705 (.A0(n_101),
	.A1(n_139),
	.B0(n_140),
	.C0(n_71),
	.Y(n_154));
   AOI21X1 g3512__5122 (.A0(n_133),
	.A1(n_112),
	.B0(d[48]),
	.Y(n_153));
   OAI221XL g3517__7098 (.A0(n_129),
	.A1(n_58),
	.B0(n_22),
	.B1(n_50),
	.C0(n_52),
	.Y(n_151));
   AOI21X1 g3518__6131 (.A0(n_122),
	.A1(n_134),
	.B0(n_88),
	.Y(n_150));
   AOI21X1 g3519__1881 (.A0(n_128),
	.A1(n_62),
	.B0(n_111),
	.Y(n_149));
   AOI211X1 g3520__5115 (.A0(n_145),
	.A1(d[31]),
	.B0(n_127),
	.C0(n_120),
	.Y(n_148));
   NAND3X1 g3528__7482 (.A(n_135),
	.B(n_142),
	.C(n_143),
	.Y(v));
   NAND4XL g3527__4733 (.A(n_145),
	.B(n_229),
	.C(n_74),
	.D(n_126),
	.Y(q[5]));
   OAI21XL g3516__6161 (.A0(n_143),
	.A1(n_125),
	.B0(n_142),
	.Y(q[4]));
   AOI21X1 g3521__2883 (.A0(n_34),
	.A1(n_29),
	.B0(n_137),
	.Y(n_138));
   NOR2BX1 g3523__2346 (.AN(n_145),
	.B(d[30]),
	.Y(n_136));
   AND4X2 g3535__1666 (.A(n_134),
	.B(n_121),
	.C(n_87),
	.D(n_105),
	.Y(n_135));
   AOI2BB1XL g3522__7410 (.A0N(n_103),
	.A1N(d[46]),
	.B0(d[47]),
	.Y(n_133));
   OAI21X1 g3524__6417 (.A0(n_97),
	.A1(d[6]),
	.B0(n_9),
	.Y(n_132));
   OAI2BB1X1 g3526__5477 (.A0N(n_79),
	.A1N(n_106),
	.B0(n_130),
	.Y(n_131));
   AOI31XL g3537__2398 (.A0(n_84),
	.A1(n_31),
	.A2(n_45),
	.B0(n_82),
	.Y(n_129));
   NAND2X1 g3531__5107 (.A(n_99),
	.B(n_53),
	.Y(n_128));
   AOI211XL g3533__6260 (.A0(n_72),
	.A1(d[58]),
	.B0(n_126),
	.C0(n_92),
	.Y(n_127));
   NAND4BXL g3539__4319 (.AN(d[33]),
	.B(n_229),
	.C(n_113),
	.D(n_76),
	.Y(n_125));
   NAND3X1 g3534__8428 (.A(n_123),
	.B(n_47),
	.C(n_26),
	.Y(n_137));
   OAI21XL g3540__5526 (.A0(n_121),
	.A1(n_117),
	.B0(n_118),
	.Y(n_122));
   NOR2X1 g3530__6783 (.A(n_93),
	.B(n_107),
	.Y(n_120));
   NOR2XL g3529__3680 (.A(n_98),
	.B(d[28]),
	.Y(n_119));
   NOR2BX1 g3547__1617 (.AN(n_118),
	.B(n_117),
	.Y(n_143));
   NOR3X1 g3554__2802 (.A(n_116),
	.B(n_115),
	.C(n_94),
	.Y(n_142));
   AND3X2 g3541__1705 (.A(n_114),
	.B(n_77),
	.C(n_113),
	.Y(n_145));
   OAI211X1 g3532__5122 (.A0(n_40),
	.A1(d[39]),
	.B0(n_75),
	.C0(n_113),
	.Y(n_112));
   OAI21XL g3538__8246 (.A0(n_110),
	.A1(n_65),
	.B0(n_44),
	.Y(n_111));
   AOI21XL g3551__7098 (.A0(n_69),
	.A1(n_104),
	.B0(n_91),
	.Y(n_109));
   NOR2BX1 g3544__6131 (.AN(n_126),
	.B(n_107),
	.Y(n_108));
   AOI2BB1XL g3543__1881 (.A0N(n_39),
	.A1N(d[16]),
	.B0(d[17]),
	.Y(n_106));
   NOR4BX1 g3570__5115 (.AN(n_83),
	.B(n_104),
	.C(d[1]),
	.D(d[0]),
	.Y(n_105));
   AOI2BB1XL g3542__7482 (.A0N(n_55),
	.A1N(d[44]),
	.B0(d[45]),
	.Y(n_103));
   NAND2X1 g3559__6161 (.A(n_95),
	.B(n_80),
	.Y(n_116));
   NOR2X1 g3560__9315 (.A(n_100),
	.B(n_102),
	.Y(n_118));
   AOI21X1 g3546__9945 (.A0(n_64),
	.A1(n_90),
	.B0(n_100),
	.Y(n_101));
   OAI2BB1X1 g3548__2883 (.A0N(n_28),
	.A1N(n_38),
	.B0(n_63),
	.Y(n_99));
   AOI2BB1X1 g3549__2346 (.A0N(n_43),
	.A1N(d[26]),
	.B0(d[27]),
	.Y(n_98));
   AOI21X1 g3552__7410 (.A0(n_95),
	.A1(n_115),
	.B0(n_94),
	.Y(n_96));
   AOI2BB1X1 g3545__6417 (.A0N(n_57),
	.A1N(d[54]),
	.B0(d[55]),
	.Y(n_93));
   NOR2X2 g3553__5477 (.A(n_110),
	.B(n_60),
	.Y(n_123));
   NOR2XL g3556__2398 (.A(n_61),
	.B(d[63]),
	.Y(n_92));
   NOR2X1 g3558__5107 (.A(n_91),
	.B(n_68),
	.Y(n_121));
   NOR2X1 g3561__6260 (.A(n_139),
	.B(n_70),
	.Y(n_134));
   OR2X2 g3562__4319 (.A(n_90),
	.B(n_89),
	.Y(n_117));
   INVXL g3565 (.A(n_87),
	.Y(n_88));
   OAI21XL g3567__5526 (.A0(n_25),
	.A1(n_27),
	.B0(n_48),
	.Y(n_86));
   AOI21X1 g3569__6783 (.A0(n_18),
	.A1(n_66),
	.B0(d[47]),
	.Y(n_85));
   OAI21XL g3571__3680 (.A0(n_24),
	.A1(n_83),
	.B0(n_54),
	.Y(n_84));
   OAI21XL g3572__1617 (.A0(n_21),
	.A1(n_46),
	.B0(n_32),
	.Y(n_82));
   INVXL g3595 (.A(n_80),
	.Y(n_81));
   OAI21XL g3555__2802 (.A0(n_16),
	.A1(d[11]),
	.B0(n_78),
	.Y(n_79));
   NOR2BX1 g3557__1705 (.AN(n_76),
	.B(d[48]),
	.Y(n_77));
   OAI21XL g3568__5122 (.A0(n_0),
	.A1(d[34]),
	.B0(n_41),
	.Y(n_75));
   NOR4BX1 g3566__8246 (.AN(n_19),
	.B(d[33]),
	.C(d[55]),
	.D(d[53]),
	.Y(n_74));
   NOR2BX1 g3574__7098 (.AN(n_113),
	.B(n_73),
	.Y(n_87));
   NOR2BX1 g3564__6131 (.AN(n_72),
	.B(d[57]),
	.Y(n_126));
   INVXL g3576 (.A(n_70),
	.Y(n_71));
   INVXL g3577 (.A(n_68),
	.Y(n_69));
   NAND3BX1 g3602__1881 (.AN(d[47]),
	.B(n_66),
	.C(n_65),
	.Y(n_67));
   NOR3X1 g3606__5115 (.A(n_20),
	.B(d[50]),
	.C(d[48]),
	.Y(n_80));
   INVX1 g3597 (.A(n_64),
	.Y(n_102));
   NAND4X1 g3575__7482 (.A(n_37),
	.B(n_63),
	.C(n_62),
	.D(n_15),
	.Y(n_110));
   AOI21X1 g3578__4733 (.A0(n_2),
	.A1(d[60]),
	.B0(d[62]),
	.Y(n_61));
   NAND2X1 g3579__6161 (.A(n_66),
	.B(n_59),
	.Y(n_60));
   NAND2X1 g3580__9315 (.A(n_51),
	.B(n_49),
	.Y(n_58));
   AOI21X1 g3581__9945 (.A0(n_6),
	.A1(d[51]),
	.B0(d[53]),
	.Y(n_57));
   AOI21XL g3582__2883 (.A0(n_3),
	.A1(d[1]),
	.B0(d[3]),
	.Y(n_56));
   AOI21XL g3583__2346 (.A0(n_1),
	.A1(d[41]),
	.B0(d[43]),
	.Y(n_55));
   NAND2X1 g3584__1666 (.A(n_54),
	.B(n_23),
	.Y(n_104));
   AND2X2 g3586__7410 (.A(n_53),
	.B(n_63),
	.Y(n_95));
   NAND2X1 g3587__6417 (.A(n_52),
	.B(n_51),
	.Y(n_90));
   NAND2X1 g3588__5477 (.A(n_50),
	.B(n_49),
	.Y(n_89));
   NAND2X1 g3589__2398 (.A(n_48),
	.B(n_47),
	.Y(n_70));
   NAND2X1 g3590__5107 (.A(n_46),
	.B(n_45),
	.Y(n_68));
   NAND2X1 g3585__6260 (.A(n_44),
	.B(n_62),
	.Y(n_94));
   AOI21X1 g3600__4319 (.A0(n_7),
	.A1(d[23]),
	.B0(d[25]),
	.Y(n_43));
   AOI21X1 g3598__8428 (.A0(n_5),
	.A1(d[36]),
	.B0(d[38]),
	.Y(n_40));
   AOI21X1 g3599__5526 (.A0(n_4),
	.A1(d[13]),
	.B0(d[15]),
	.Y(n_39));
   OAI21XL g3605__6783 (.A0(d[51]),
	.A1(d[50]),
	.B0(n_37),
	.Y(n_38));
   AOI21X1 g3601__3680 (.A0(n_8),
	.A1(d[19]),
	.B0(d[21]),
	.Y(n_36));
   NAND2X1 g3603__1617 (.A(n_30),
	.B(n_11),
	.Y(n_35));
   OAI21XL g3604__2802 (.A0(d[27]),
	.A1(d[26]),
	.B0(n_33),
	.Y(n_34));
   NAND2X1 g3591__1705 (.A(n_32),
	.B(n_31),
	.Y(n_91));
   AND2X2 g3613__5122 (.A(n_30),
	.B(n_13),
	.Y(n_64));
   NAND2X1 g3592__8246 (.A(n_29),
	.B(n_33),
	.Y(n_100));
   NAND2X1 g3612__7098 (.A(n_14),
	.B(n_12),
	.Y(n_107));
   NAND2X1 g3594__6131 (.A(n_37),
	.B(n_28),
	.Y(n_115));
   NAND2X1 g3593__1881 (.A(n_27),
	.B(n_26),
	.Y(n_139));
   INVXL g3638 (.A(n_47),
	.Y(n_25));
   INVXL g3635 (.A(n_23),
	.Y(n_24));
   INVXL g3637 (.A(n_51),
	.Y(n_22));
   INVXL g3636 (.A(n_31),
	.Y(n_21));
   NOR3X1 g3608__5115 (.A(d[63]),
	.B(d[61]),
	.C(d[59]),
	.Y(n_72));
   NOR3X1 g3607__7482 (.A(d[16]),
	.B(d[14]),
	.C(d[12]),
	.Y(n_78));
   INVXL g3616 (.A(n_19),
	.Y(n_20));
   INVXL g3615 (.A(n_17),
	.Y(n_18));
   NOR4X2 g3611__4733 (.A(d[38]),
	.B(d[36]),
	.C(d[34]),
	.D(d[32]),
	.Y(n_76));
   NOR3X1 g3609__6161 (.A(d[39]),
	.B(d[37]),
	.C(d[35]),
	.Y(n_41));
   OR4X2 g3610__9315 (.A(d[45]),
	.B(d[43]),
	.C(d[47]),
	.D(d[41]),
	.Y(n_73));
   NOR2BXL g3639__2883 (.AN(d[9]),
	.B(d[10]),
	.Y(n_16));
   NOR2X1 g3643__2346 (.A(d[49]),
	.B(d[48]),
	.Y(n_15));
   NOR2X1 g3640__1666 (.A(d[60]),
	.B(d[58]),
	.Y(n_14));
   NOR2X1 g3622__7410 (.A(d[59]),
	.B(d[58]),
	.Y(n_53));
   NOR2X1 g3624__6417 (.A(d[17]),
	.B(d[16]),
	.Y(n_49));
   NOR2X1 g3625__5477 (.A(d[55]),
	.B(d[54]),
	.Y(n_28));
   NOR2X1 g3629__2398 (.A(d[41]),
	.B(d[40]),
	.Y(n_59));
   NOR2X1 g3626__5107 (.A(d[20]),
	.B(d[18]),
	.Y(n_130));
   NOR2X1 g3627__6260 (.A(d[63]),
	.B(d[62]),
	.Y(n_44));
   NOR2X1 g3619__4319 (.A(d[15]),
	.B(d[14]),
	.Y(n_32));
   NOR2X1 g3630__8428 (.A(d[33]),
	.B(d[32]),
	.Y(n_26));
   NOR2X1 g3620__5526 (.A(d[43]),
	.B(d[42]),
	.Y(n_17));
   NOR2X1 g3621__6783 (.A(d[31]),
	.B(d[30]),
	.Y(n_29));
   NOR2X1 g3633__3680 (.A(d[57]),
	.B(d[56]),
	.Y(n_63));
   NOR2X1 g3654__1617 (.A(d[13]),
	.B(d[12]),
	.Y(n_31));
   NOR2X1 g3634__2802 (.A(d[53]),
	.B(d[52]),
	.Y(n_37));
   NOR2X1 g3632__1705 (.A(d[45]),
	.B(d[44]),
	.Y(n_66));
   NOR2X2 g3631__5122 (.A(d[61]),
	.B(d[60]),
	.Y(n_62));
   NOR2X1 g3642__8246 (.A(d[27]),
	.B(d[25]),
	.Y(n_13));
   NOR2X1 g3617__7098 (.A(d[62]),
	.B(d[56]),
	.Y(n_12));
   NOR2X1 g3641__6131 (.A(d[28]),
	.B(d[22]),
	.Y(n_11));
   NOR2X1 g3618__1881 (.A(d[10]),
	.B(d[8]),
	.Y(n_10));
   NOR2X1 g3651__5115 (.A(d[5]),
	.B(d[4]),
	.Y(n_23));
   NOR2X1 g3652__7482 (.A(d[9]),
	.B(d[8]),
	.Y(n_45));
   NOR2X1 g3623__4733 (.A(d[51]),
	.B(d[49]),
	.Y(n_19));
   NOR2X1 g3645__6161 (.A(d[7]),
	.B(d[6]),
	.Y(n_54));
   NOR2X1 g3644__9315 (.A(d[35]),
	.B(d[34]),
	.Y(n_27));
   NOR2X1 g3648__9945 (.A(d[11]),
	.B(d[10]),
	.Y(n_46));
   NOR2X1 g3646__2883 (.A(d[39]),
	.B(d[38]),
	.Y(n_48));
   NOR2X1 g3647__2346 (.A(d[3]),
	.B(d[2]),
	.Y(n_83));
   NOR2X1 g3628__1666 (.A(d[19]),
	.B(d[18]),
	.Y(n_50));
   NOR2X1 g3650__7410 (.A(d[26]),
	.B(d[24]),
	.Y(n_30));
   NOR2X1 g3649__6417 (.A(d[23]),
	.B(d[22]),
	.Y(n_52));
   NOR2X1 g3653__5477 (.A(d[29]),
	.B(d[28]),
	.Y(n_33));
   NOR2X1 g3655__2398 (.A(d[21]),
	.B(d[20]),
	.Y(n_51));
   NOR2X1 g3656__5107 (.A(d[37]),
	.B(d[36]),
	.Y(n_47));
   INVX1 g3657 (.A(d[7]),
	.Y(n_9));
   INVX1 g3658 (.A(d[20]),
	.Y(n_8));
   INVX1 g3659 (.A(d[24]),
	.Y(n_7));
   INVX1 g3660 (.A(d[52]),
	.Y(n_6));
   INVX1 g3667 (.A(d[46]),
	.Y(n_65));
   INVX1 g3665 (.A(d[37]),
	.Y(n_5));
   INVX1 g3664 (.A(d[14]),
	.Y(n_4));
   INVX1 g3663 (.A(d[2]),
	.Y(n_3));
   INVX1 g3666 (.A(d[61]),
	.Y(n_2));
   INVX1 g3661 (.A(d[42]),
	.Y(n_1));
   INVX1 g3662 (.A(d[33]),
	.Y(n_0));
   NOR2BX1 g2 (.AN(n_41),
	.B(n_73),
	.Y(n_229));
endmodule

