/*
###############################################################
#  Generated by:      Cadence Innovus 20.14-s095_1
#  OS:                Linux x86_64(Host ID cad28)
#  Generated on:      Tue Sep 30 16:24:05 2025
#  Design:            pe64_lookahead
#  Command:           saveNetlist pe64_lookahead.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Sep 30 2025 13:58:13 IST (Sep 30 2025 08:28:13 UTC)
// Verification Directory fv/pe64_lookahead 
module pe64_lookahead (
	d, 
	q, 
	v);
   input [63:0] d;
   output [5:0] q;
   output v;

   // Internal wires
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_65;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;
   wire n_78;
   wire n_79;
   wire n_80;
   wire n_81;
   wire n_82;
   wire n_83;
   wire n_84;
   wire n_152;

   OAI21XL g2731__2398 (.A0(n_84),
	.A1(n_81),
	.B0(n_83),
	.Y(q[0]));
   NAND2BXL g2732__5107 (.AN(n_84),
	.B(n_83),
	.Y(q[1]));
   NAND3BXL g2734__6260 (.AN(d[62]),
	.B(n_22),
	.C(n_82),
	.Y(n_84));
   NOR2XL g2733__4319 (.A(d[63]),
	.B(n_80),
	.Y(n_83));
   AOI221XL g2737__8428 (.A0(d[38]),
	.A1(n_28),
	.B0(d[50]),
	.B1(n_17),
	.C0(n_78),
	.Y(n_82));
   NOR2XL g2735__5526 (.A(d[61]),
	.B(n_79),
	.Y(n_81));
   NAND4XL g2736__6783 (.A(n_13),
	.B(n_24),
	.C(n_26),
	.D(n_77),
	.Y(n_80));
   NAND4XL g2738__3680 (.A(n_18),
	.B(n_29),
	.C(n_65),
	.D(n_74),
	.Y(n_79));
   NAND2XL g2740__1617 (.A(n_68),
	.B(n_76),
	.Y(n_78));
   AOI211XL g2739__2802 (.A0(n_75),
	.A1(d[55]),
	.B0(n_70),
	.C0(n_69),
	.Y(n_77));
   AOI21XL g2741__1705 (.A0(d[54]),
	.A1(n_75),
	.B0(n_72),
	.Y(n_76));
   AOI21XL g2742__5122 (.A0(d[53]),
	.A1(n_75),
	.B0(n_71),
	.Y(n_74));
   NAND2XL g2746__8246 (.A(n_63),
	.B(n_62),
	.Y(q[2]));
   NAND4XL g2744__7098 (.A(n_49),
	.B(n_37),
	.C(n_55),
	.D(n_60),
	.Y(n_72));
   NAND4XL g2745__6131 (.A(n_46),
	.B(n_40),
	.C(n_51),
	.D(n_59),
	.Y(n_71));
   NAND4XL g2743__1881 (.A(n_50),
	.B(n_41),
	.C(n_54),
	.D(n_56),
	.Y(n_70));
   AO22X1 g2749__5115 (.A0(d[3]),
	.A1(n_67),
	.B0(d[59]),
	.B1(n_152),
	.Y(n_69));
   AOI22XL g2750__7482 (.A0(n_67),
	.A1(d[2]),
	.B0(n_152),
	.B1(d[58]),
	.Y(n_68));
   AOI22XL g2751__4733 (.A0(n_67),
	.A1(d[1]),
	.B0(n_152),
	.B1(d[57]),
	.Y(n_65));
   NAND2XL g2747__6161 (.A(n_63),
	.B(n_61),
	.Y(q[3]));
   OAI21XL g2748__9315 (.A0(n_36),
	.A1(n_10),
	.B0(n_61),
	.Y(n_62));
   AOI22XL g2756__9945 (.A0(n_58),
	.A1(d[6]),
	.B0(n_57),
	.B1(d[10]),
	.Y(n_60));
   AOI22XL g2758__2883 (.A0(n_58),
	.A1(d[5]),
	.B0(n_57),
	.B1(d[9]),
	.Y(n_59));
   AOI22XL g2753__2346 (.A0(n_58),
	.A1(d[7]),
	.B0(n_57),
	.B1(d[11]),
	.Y(n_56));
   AOI22XL g2757__1666 (.A0(n_53),
	.A1(d[14]),
	.B0(n_52),
	.B1(d[18]),
	.Y(n_55));
   AND2X1 g2762__7410 (.A(n_35),
	.B(n_58),
	.Y(n_67));
   AOI22XL g2752__6417 (.A0(n_53),
	.A1(d[15]),
	.B0(n_52),
	.B1(d[19]),
	.Y(n_54));
   AOI22XL g2755__5477 (.A0(n_53),
	.A1(d[13]),
	.B0(n_52),
	.B1(d[17]),
	.Y(n_51));
   NOR2XL g2754__2398 (.A(n_11),
	.B(n_45),
	.Y(n_61));
   NOR2XL g2761__5107 (.A(n_12),
	.B(n_33),
	.Y(n_63));
   AOI22XL g2759__6260 (.A0(n_48),
	.A1(d[23]),
	.B0(n_47),
	.B1(d[27]),
	.Y(n_50));
   AOI22XL g2764__4319 (.A0(n_48),
	.A1(d[22]),
	.B0(n_47),
	.B1(d[26]),
	.Y(n_49));
   AOI22XL g2766__8428 (.A0(n_48),
	.A1(d[21]),
	.B0(n_47),
	.B1(d[25]),
	.Y(n_46));
   OAI222XL g2767__5526 (.A0(n_30),
	.A1(q[5]),
	.B0(n_42),
	.B1(n_34),
	.C0(q[4]),
	.C1(n_19),
	.Y(n_45));
   AND2X1 g2769__6783 (.A(n_42),
	.B(n_57),
	.Y(n_58));
   AOI22XL g2760__3680 (.A0(n_39),
	.A1(d[31]),
	.B0(n_38),
	.B1(d[35]),
	.Y(n_41));
   AOI22XL g2763__1617 (.A0(n_39),
	.A1(d[29]),
	.B0(n_38),
	.B1(d[33]),
	.Y(n_40));
   AOI22XL g2765__2802 (.A0(n_39),
	.A1(d[30]),
	.B0(n_38),
	.B1(d[34]),
	.Y(n_37));
   OAI222XL g2771__1705 (.A0(n_35),
	.A1(n_34),
	.B0(n_25),
	.B1(q[4]),
	.C0(q[5]),
	.C1(n_32),
	.Y(n_36));
   OAI222XL g2772__5122 (.A0(n_31),
	.A1(n_34),
	.B0(n_15),
	.B1(q[4]),
	.C0(q[5]),
	.C1(n_20),
	.Y(n_33));
   AND2X1 g2768__8246 (.A(n_32),
	.B(n_48),
	.Y(n_52));
   NOR2BXL g2778__7098 (.AN(n_31),
	.B(n_34),
	.Y(n_57));
   AND2X1 g2775__6131 (.A(n_30),
	.B(n_47),
	.Y(n_48));
   AOI22XL g2770__1881 (.A0(n_28),
	.A1(d[37]),
	.B0(n_23),
	.B1(d[41]),
	.Y(n_29));
   OR3XL g2782__5115 (.A(n_7),
	.B(n_8),
	.C(q[5]),
	.Y(v));
   INVXL g2781 (.A(n_53),
	.Y(n_34));
   NAND2XL g2773__7482 (.A(d[39]),
	.B(n_28),
	.Y(n_26));
   AND2X1 g2774__4733 (.A(n_25),
	.B(n_28),
	.Y(n_38));
   AOI22XL g2776__6161 (.A0(n_23),
	.A1(d[43]),
	.B0(n_21),
	.B1(d[47]),
	.Y(n_24));
   AOI22XL g2777__9315 (.A0(n_23),
	.A1(d[42]),
	.B0(n_21),
	.B1(d[46]),
	.Y(n_22));
   NOR2BXL g2779__9945 (.AN(n_20),
	.B(q[5]),
	.Y(n_47));
   NOR2XL g2784__2883 (.A(q[5]),
	.B(q[4]),
	.Y(n_53));
   AND2X1 g2780__2346 (.A(n_19),
	.B(n_23),
	.Y(n_28));
   AOI22XL g2783__1666 (.A0(n_21),
	.A1(d[45]),
	.B0(n_17),
	.B1(d[49]),
	.Y(n_18));
   CLKINVX1 g2785 (.A(n_39),
	.Y(q[5]));
   OAI21XL g2788__7410 (.A0(n_9),
	.A1(n_16),
	.B0(n_21),
	.Y(q[4]));
   NOR2XL g2786__6417 (.A(n_16),
	.B(n_14),
	.Y(n_39));
   NOR2BXL g2787__5477 (.AN(n_15),
	.B(n_14),
	.Y(n_23));
   INVXL g2789 (.A(n_14),
	.Y(n_21));
   NAND2XL g2790__2398 (.A(n_6),
	.B(n_17),
	.Y(n_14));
   NAND2XL g2791__5107 (.A(d[51]),
	.B(n_17),
	.Y(n_13));
   NOR3X1 g2793__6260 (.A(n_12),
	.B(n_11),
	.C(n_10),
	.Y(n_17));
   NOR2XL g2797__4319 (.A(n_12),
	.B(n_11),
	.Y(n_75));
   INVXL g2794 (.A(n_8),
	.Y(n_9));
   CLKINVX1 g2806 (.A(n_152),
	.Y(n_12));
   NAND4XL g2795__8428 (.A(n_4),
	.B(n_42),
	.C(n_35),
	.D(n_31),
	.Y(n_7));
   NAND4XL g2792__5526 (.A(n_5),
	.B(n_15),
	.C(n_25),
	.D(n_19),
	.Y(n_16));
   NAND4XL g2796__6783 (.A(n_3),
	.B(n_30),
	.C(n_32),
	.D(n_20),
	.Y(n_8));
   NOR4X1 g2798__1617 (.A(d[48]),
	.B(d[49]),
	.C(d[50]),
	.D(d[51]),
	.Y(n_6));
   OR4XL g2810__2802 (.A(d[52]),
	.B(d[53]),
	.C(d[54]),
	.D(d[55]),
	.Y(n_10));
   NOR4X1 g2799__1705 (.A(d[24]),
	.B(d[27]),
	.C(d[25]),
	.D(d[26]),
	.Y(n_30));
   NOR4X1 g2800__5122 (.A(d[44]),
	.B(d[46]),
	.C(d[45]),
	.D(d[47]),
	.Y(n_15));
   NOR4X1 g2801__8246 (.A(d[20]),
	.B(d[22]),
	.C(d[21]),
	.D(d[23]),
	.Y(n_32));
   NOR4X1 g2802__7098 (.A(d[4]),
	.B(d[5]),
	.C(d[6]),
	.D(d[7]),
	.Y(n_35));
   NOR4X1 g2803__6131 (.A(d[40]),
	.B(d[43]),
	.C(d[41]),
	.D(d[42]),
	.Y(n_19));
   NOR4X1 g2804__1881 (.A(d[36]),
	.B(d[39]),
	.C(d[37]),
	.D(d[38]),
	.Y(n_25));
   NOR4X1 g2809__5115 (.A(d[32]),
	.B(d[35]),
	.C(d[33]),
	.D(d[34]),
	.Y(n_5));
   NOR4X1 g2808__7482 (.A(d[0]),
	.B(d[2]),
	.C(d[1]),
	.D(d[3]),
	.Y(n_4));
   NOR4X1 g2807__4733 (.A(d[16]),
	.B(d[18]),
	.C(d[17]),
	.D(d[19]),
	.Y(n_3));
   NOR4X1 g2805__9315 (.A(d[28]),
	.B(d[30]),
	.C(d[29]),
	.D(d[31]),
	.Y(n_20));
   OR4XL g2812__9945 (.A(d[56]),
	.B(d[59]),
	.C(d[57]),
	.D(d[58]),
	.Y(n_11));
   NOR4X1 g2813__2883 (.A(d[12]),
	.B(d[14]),
	.C(d[13]),
	.D(d[15]),
	.Y(n_31));
   NOR4X1 g2811__2346 (.A(d[8]),
	.B(d[11]),
	.C(d[9]),
	.D(d[10]),
	.Y(n_42));
   NOR4X1 g2818 (.A(d[61]),
	.B(d[63]),
	.C(d[60]),
	.D(d[62]),
	.Y(n_152));
endmodule

